### ISSUE TITLE
Device Connected 2x on startup

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#173]
In my current Installation on startup a Device connects 2-times (firmware 0.6.2)

Everything works as expected, so is this behaviour ok...

Best regards, and thanx for you work

Andreas

---- LOG From Server ----
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
null
Connection from: ::ffff:217.92.xxx.xxx - Device ID: 3d004b001051353338363333 Connection ID: 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Error: No device state!
Connected Devices 1  - Sockets 1
1 : Device disconnected: socket close [object Object]
Session ended for device with ID: 3d004b001051353338363333 with connectionKey: _1
Connection from: ::ffff:217.92.xxx.xxx - Device ID: 3d004b001051353338363333 Connection ID: 2
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1

**Comment by jlkalberer** [comment]
I can't reproduce this. Could you try deleting your `node_modules` folder, doing a git pull, and then reinstalling?

**Comment by haeferer** [comment]
Already done. The installation is a Docker Image which is build everytime from Scratch 
(on Alpine Node including GIT and GYP etc.).
So this is a COMPLETE from Scratch installation ... 
Maybe "Error: No device state!" is the problem.
The image only contains permanent data in "/data" . So if there is anything
persistent needed outside this directory this may cause the problem ?

**Comment by haeferer** [comment]
For your info:

started with 

ENTRYPOINT ["npm", "run", "start:prod"]

this is execute inside the Image on Build Time

RUN apk add --no-cache git; \
    apk add --no-cache python; \
    apk add --no-cache make; \
    apk add --no-cache g++; \
    cd /usr/src/localCloud; \
    npm install -g node-gyp; \
    git clone https://github.com/Brewskey/spark-server.git; \
    cd /usr/src/localCloud/spark-server; \
    npm install; \
    npm run update-firmware; \
    npm run prebuild; \    
    npm run build; \    
    apk del python make g++

**Comment by jlkalberer** [comment]
Ok, so I could repro this once and we're aware of the bug.

What happens is when the server sends the `Describe` COAP message the device will send back two packets of data. Sometimes both of these packets don't get there on time so we reset the connection on the device.

I think in 0.6.1 they changed this behavior so it is all sent in one packet and we support that but it's still flaky.

--- 

Anyways, I don't think this is a huge issue and most times you won't see this error.

**Comment by jlkalberer** [comment]
PS. It would be awesome if you made PR with a `docker` folder under the examples where you write up how to set up the docker instance.

**Comment by haeferer** [comment]
Yep i will do this. I think docker is a good system to manage the server (including MongoDb or MessageQueue etc.) 
My own system, which uses the Server is also based on connected Docker Images (Including REDIS and RABBITMQ)

**Comment by jlkalberer** [comment]
@haeferer - can you test this again? I think I've fixed things.

**Comment by haeferer** [comment]
@jlkalberer - First test is already done. Looks good. I will test more than one Particle tomorrow.

**Comment by haeferer** [comment]
First Test was wrong. :( 

I've build a image from latest commit c182732 (are your changes already included?)

Problem is still the same

Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
Connected Devices 0  - Sockets 0
null
Connection from: ::ffff:217.92.242.230 - Device ID: 3d004b001051353338363333 Connection ID: 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Error: No device state!
Connected Devices 1  - Sockets 1
1 : Device disconnected: socket close [object Object]
Connection from: ::ffff:217.92.242.230 - Device ID: 3d004b001051353338363333 Connection ID: 2
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1

**Comment by jlkalberer** [comment]
So you're just testing with a single device and seeing that happen?

Is the server/device on your local network?

The positive here is that the device at least connects. I really want to figure this out because I think the solution will allow the server to have 1k devices connect all at once.

**Comment by haeferer** [comment]
Right now it's only a single device (maybe only the FIRST ONE connecting to a server ???
But it's connected the FULL WAY 
- Local WLAN
- Internet Provider
- Hosting Provider
- DMZ/FireWall 
- Local Server
overall 20-50ms PingTime

**Comment by haeferer** [comment]
__Interessting Effect__
The Problem seems to be only for the FIRST Device:
```
Connection from: ::ffff:217.92.242.230 - Device ID: 44002c000547353138383138 Connection ID: 1
Connected Devices 1  - Sockets 1
Error: No device state!
Connected Devices 1  - Sockets 1
1 : Device disconnected: socket close [object Object]
Session ended for device with ID: 44002c000547353138383138 with connectionKey: _1
Connection from: ::ffff:217.92.242.230 - Device ID: 44002c000547353138383138 Connection ID: 2
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connected Devices 1  - Sockets 1
Connection from: ::ffff:217.92.242.230 - Device ID: 3d004b001051353338363333 Connection ID: 3
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
```
If booth devices are available from Start sometimes it works for the second , or fails for booth: 


``` 
null
Connection from: ::ffff:217.92.242.230 - Device ID: 44002c000547353138383138 Connection ID: 1
Connection from: ::ffff:217.92.242.230 - Device ID: 3d004b001051353338363333 Connection ID: 2
Connected Devices 2  - Sockets 2
Error: No device state!
Error: No device state!
Connected Devices 2  - Sockets 2
1 : Device disconnected: socket close [object Object]
Session ended for device with ID: 44002c000547353138383138 with connectionKey: _1
1 : Device disconnected: socket close [object Object]
Session ended for device with ID: 3d004b001051353338363333 with connectionKey: _2
Connection from: ::ffff:217.92.242.230 - Device ID: 44002c000547353138383138 Connection ID: 3
Connection from: ::ffff:217.92.242.230 - Device ID: 3d004b001051353338363333 Connection ID: 4
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
```
If there are 2 Devices, sometimes it works just fine (i have not seen this for only ONE Device)

```
null
Connection from: ::ffff:217.92.242.230 - Device ID: 3d004b001051353338363333 Connection ID: 2
Connection from: ::ffff:217.92.242.230 - Device ID: 44002c000547353138383138 Connection ID: 1
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
Connected Devices 2  - Sockets 2
```

**Comment by jlkalberer** [comment]
Thanks. We are currently looking into ways to fix the handshake. It should be a few weeks and then this should be resolved.

**Comment by AntonPuko** [comment]
@haeferer https://github.com/Brewskey/spark-server/commit/c1fc67426f0fae1cb2e168ae7c299c9bd9d328b1 try with the last version. deviceState errors and double reconnects should go away. But the changes may introduce many other bugs, so feel free to open issue, if you find some :)

**Comment by haeferer** [comment]
Seems to be working since commit 066f863e642a5c067918ec733102bc74fee30c87
